# Generated by Django 4.2.30 on 2026-07-05 08:06

from django.db import migrations, models

import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_contest_replay_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='full_size',
            field=models.CharField(blank=True, max_length=1000, validators=[judge.models.profile.validate_relative_or_absolute], verbose_name='full size badge URL'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='mini',
            field=models.CharField(blank=True, max_length=1000, validators=[judge.models.profile.validate_relative_or_absolute], verbose_name='mini badge URL'),
        ),
    ]
