# Generated by Django 4.2.27 on 2026-07-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_alter_badge_full_size_alter_badge_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, the ban will be automatically lifted after this time.', null=True),
        ),
    ]
