# Generated by Django 4.2.27 on 2026-07-21 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import judge.models.profile


def migrate_nameplates(apps, schema_editor):
    Profile = apps.get_model('judge', 'Profile')
    Nameplate = apps.get_model('judge', 'Nameplate')

    VALID_RANKS = dict(getattr(settings, 'VNOJ_DISPLAY_RANKS', {}))
    EXCLUDED_RANKS = {'user', 'banned'}

    ranks = set(
        Profile.objects.values_list(
            'display_rank',
            flat=True,
        ),
    )

    ranks |= set(VALID_RANKS)
    ranks -= EXCLUDED_RANKS

    for rank in ranks:
        Nameplate.objects.get_or_create(
            class_name=rank,
            buyable=False,
            defaults={
                'name': VALID_RANKS.get(rank, rank),
            },
        )

    nameplates = {
        n.class_name: n
        for n in Nameplate.objects.all()
    }

    for profile in Profile.objects.exclude(display_rank__in=('user', 'banned')).iterator():
        nameplate = nameplates.get(profile.display_rank)

        if not nameplate:
            continue

        profile.active_nameplate = nameplate
        profile.save(update_fields=['active_nameplate'])

        profile.nameplates.add(nameplate)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0234_alter_contest_authors_alter_contest_curators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nameplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable Nameplate')),
                ('buyable', models.BooleanField(default=True, verbose_name='Buyable Nameplate')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the Nameplate')),
                ('class_name', models.CharField(help_text='Example: cute, legendary, halloween', max_length=64, unique=True, verbose_name='CSS Nameplate class name')),
                ('cost', models.PositiveIntegerField(default=0, help_text='Cost in Connhen. Set to 0 for free nameplates.', verbose_name='cost')),
                ('image', models.CharField(blank=True, help_text='Nameplate image URL. Reserved for future use.', max_length=1000, validators=[judge.models.profile.validate_relative_or_absolute], verbose_name='nameplate image URL')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='connhen',
            field=models.IntegerField(default=0, help_text='The amount of Connhen (Spiders) owned by the user.', verbose_name='Connhen'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_connhen_balance',
            field=models.BooleanField(default=True, help_text='Display Connhen balance on on navigation bar.', verbose_name='Display Connhen balance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(default='user', max_length=64, verbose_name='display rank'),
        ),
        migrations.AddField(
            model_name='profile',
            name='active_nameplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.nameplate', verbose_name='active nameplate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nameplates',
            field=models.ManyToManyField(blank=True, related_name='owners', to='judge.nameplate', verbose_name='nameplates'),
        ),
        migrations.RunPython(
            migrate_nameplates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
