# Generated by Django 4.2.27 on 2026-07-21 17:02

import django.db.models.deletion
from django.db import migrations, models

import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0235_nameplate_profile_connhen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable Banner')),
                ('buyable', models.BooleanField(default=True, verbose_name='Buyable Banner')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the Banner')),
                ('class_name', models.CharField(help_text='Example: cute, legendary, halloween', max_length=64, unique=True, verbose_name='CSS Banner class name')),
                ('cost', models.PositiveIntegerField(default=0, help_text='Cost in Connhen. Set to 0 for free banners.', verbose_name='cost')),
                ('image', models.CharField(blank=True, help_text='Banner image URL. Reserved for future use.', max_length=1000, validators=[judge.models.profile.validate_relative_or_absolute], verbose_name='banner image URL')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='active_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.banner', verbose_name='active banner'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banners',
            field=models.ManyToManyField(blank=True, related_name='owners', to='judge.banner', verbose_name='banners'),
        ),
    ]
