# Generated by Django 4.2.27 on 2026-07-24 06:50

import django.db.models.deletion
from django.db import migrations, models

import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_banner_profile_active_banner_profile_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable Avatar Frame')),
                ('buyable', models.BooleanField(default=True, verbose_name='Buyable Avatar Frame')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the Avatar Frame')),
                ('class_name', models.CharField(help_text='Example: cute, legendary, halloween', max_length=64, unique=True, verbose_name='CSS Avatar Frame class name')),
                ('cost', models.PositiveIntegerField(default=0, help_text='Cost in Connhen. Set to 0 for free avatar frames.', verbose_name='cost')),
                ('image', models.CharField(blank=True, help_text='Avatar Frame image URL. Reserved for future use.', max_length=1000, validators=[judge.models.profile.validate_relative_or_absolute], verbose_name='Avatar Frame image URL')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='active_avatar_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.avatarframe', verbose_name='active avatar frame'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_frames',
            field=models.ManyToManyField(blank=True, related_name='owners', to='judge.avatarframe', verbose_name='avatar frames'),
        ),
    ]
