# Generated by Django 4.2.27 on 2026-07-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_alter_contest_authors_alter_contest_curators_and_more'),
        ('judge', '0237_avatarframe_profile_active_avatar_frame_and_more'),
    ]

    operations = [
    ]
