# Generated by Django 4.2.27 on 2026-08-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_organization_problem_tag'),
        ('judge', '0237_avatarframe_profile_active_avatar_frame_and_more'),
    ]

    operations = [
    ]
