# Generated by Django 4.2.30 on 2026-08-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0233_organization_notice'),
        ('judge', '0238_merge_20260823_0658'),
    ]

    operations = [
    ]
