# Generated by Django 4.2.27 on 2026-08-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0234_problem_archived_at'),
        ('judge', '0239_merge_20260823_1619'),
    ]

    operations = [
    ]
