# Generated by Django 4.2.27 on 2026-08-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0238_merge_20260728_1038'),
        ('judge', '0240_merge_20260827_1015'),
    ]

    operations = [
    ]
