# Generated by Django 4.2.30 on 2026-09-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_judge_storages'),
        ('judge', '0241_merge_20260827_1125'),
    ]

    operations = [
    ]
