# Generated by Django 4.2.30 on 2026-09-21 16:16

from django.db import migrations


def force_light_theme(apps, schema_editor):
    Profile = apps.get_model('judge', 'Profile')
    Profile.objects.filter(site_theme__in=('dark', 'auto')).update(site_theme='light')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0241_merge_20260827_1125'),
    ]

    operations = [
        migrations.RunPython(force_light_theme, noop),
    ]