# Generated by Django 4.2.30 on 2026-09-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0242_site_theme_force_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codeforces_handle',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Codeforces handle'),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_handle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Discord handle'),
        ),
    ]
