# Generated by Django 4.2.30 on 2026-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0243_add_profile_social_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='atcoder_handle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AtCoder handle'),
        ),
    ]
