# Generated by Django 4.2.30 on 2026-09-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0244_profile_atcoder_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='disqualify_reason',
            field=models.CharField(blank=True, choices=[('ai', 'AI detect'), ('copy', 'Chép code'), ('no_explanation', 'Không giải thích'), ('other', 'Khác')], default='', help_text='Why this participation was disqualified.', max_length=20, verbose_name='disqualification reason'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='disqualify_reason_detail',
            field=models.TextField(blank=True, default='', help_text='Free-form detail, only used for the "Khác" reason.', verbose_name='disqualification reason detail'),
        ),
    ]
